trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "Starting Student Mark Management System Pipeline"
  displayName: 'Start Pipeline'

- script: |
    echo "Data Input: Student Info and Subject Marks"
  displayName: 'Data Input'

- script: |
    echo "Validate Data"
  displayName: 'Validate Data'

- script: |
    echo "Store Data in Database"
  displayName: 'Store Data'

- script: |
    echo "Calculate Results (if needed)"
  displayName: 'Calculate Results'

- script: |
    echo "Generate Student Report Card (if needed)"
  displayName: 'Generate Report'

- script: |
    echo "Generate Class/Subject Reports (if needed)"
  displayName: 'Generate Class Reports'

- script: |
    echo "Display/Export Reports"
  displayName: 'Display Reports'

- script: |
    echo "Pipeline Complete"
  displayName: 'End Pipeline'